version: "3"
services:
  moderation_panel:
    build:
      context: .
      args:
        - env=pp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CURR_ENV=pp
    command: >
      ash -c "/usr/bin/supervisord -n -c /etc/supervisord.d/moderation_panel.ini"
    volumes:
      - /tmp/moderation_panel:/logs