version: "3"
services:
  moderation_panel:
    image: moderation:latest
    build:
      context: .
      args:
        - env=dev
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CURR_ENV=dev
    command: >
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - /tmp/moderation_panel:/logs