version: "3"
services:
  moderation_panel:
    build:
      context: .
      args:
        env=moderation_dev
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODERATION_PANEL_ENV=moderation_dev
    command: >
      python3.7 manage.py runserver 0.0.0.0:8000
    volumes:
      - /tmp/moderation_panel:/logs